format_version: "2.1"

services:
  - name: service1
    url: http://service1:8080 
    routes:
      - name: service1
        paths:
          - /service1
        methods:
          - GET
          - POST

  - name: service2
    url: http://service2:8081
    routes:
      - name: service2
        paths:
          - /service2
        methods:
          - GET
          - POST
