version: '3'

# networks:
#  kong-net:
#   driver: bridge

services:

  service1: 
    build: 
      context: ./service1
    environment:
      - PORT=8080
    ports:
      - "8080:8080"

  service2:
    build:
      context: ./service2
    environment:
      - PORT=8081
    ports:
      - "8081:8081"

  ###### Postgres Database for Kong

  kong-database:
    image: postgres:latest
    restart: always
    # networks:
    #   - kong-net
    environment:
      POSTGRES_USER: "kong"
      POSTGRES_DB: "kong"
      POSTGRES_PASSWORD: "kong"
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 10s
      retries: 10

  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    # networks:
    #   - kong-net
    restart: on-failure
    environment:
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    links:
      - kong-database
    depends_on:
      - kong-database

  ###### Kong Api Gateway

  kong:
    image: kong:latest
    # networks:
    #   - kong-net
    volumes:
      - ./kong.yml:/etc/kong/kong.yml 
    environment:
     - KONG_DATABASE=postgres
     - KONG_PG_HOST=kong-database
    #  - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
    #  - KONG_DECLARATIVE_CONFIG=./kong.yml
    #  - KONG_DECLARATIVE_CONFIG:/etc/kong/kong.yml
     - KONG_PG_USER=kong
     - KONG_PG_PASSWORD=kong
     - KONG_PROXY_ACCESS_LOG=/dev/stdout
     - KONG_ADMIN_ACCESS_LOG=/dev/stdout
     - KONG_PROXY_ERROR_LOG=/dev/stderr
     - KONG_ADMIN_ERROR_LOG=/dev/stderr
     - KONG_ADMIN_LISTEN=0.0.0.0:8001
     - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
     - "8000:8000"
     - "8443:8443"
     - "8001:8001"
     - "8444:8444"
     - "8002:8002"
     - "8445:8445"
     - "8003:8003"
     - "8004:8004"
    healthcheck:
      test: [ "CMD", "kong", "health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: on-failure:5
    command: "kong start"
    depends_on:
      - service1
      - service2
      - kong-database